{% set name = "yaqd-core" %}
{% set version = "2022.8.0" %}
{% set sha256 = "3b5fb979693d34ae56b04551d4786dc2cc6934d0bf5c22852939fefa49ca2572" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - appdirs
    - tomli
    - tomli-w
    - fastavro >=1.4.0
    - flit ==3.1.0
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - appdirs
    - tomli
    - tomli-w
    - fastavro >=1.4.0

test:
  imports:
    - yaqd_core

about:
  home: https://yaq.fyi
  dev_url: https://gitlab.com/yaq/yaq-python
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: Core python package for implementing yaq deamons, and associated utilities.

extra:
  recipe-maintainers:
    - untzag
    - ksunden
